// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PostuleCandidature.Model;
using System;

namespace PostuleCandidature.Migrations
{
    [DbContext(typeof(PostuleContext))]
    [Migration("20190110190638_createModel4")]
    partial class createModel4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PostuleCandidature.Model.Postulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("date");

                    b.Property<string>("email");

                    b.Property<bool>("emailSent");

                    b.Property<string>("link");

                    b.Property<string>("nomSociete");

                    b.Property<string>("poste");

                    b.Property<string>("reference");

                    b.HasKey("Id");

                    b.ToTable("postulations");
                });
#pragma warning restore 612, 618
        }
    }
}
